### PR TITLE
Fix for RETURNN updates

### PR DESCRIPTION
**Pull request by vieting**
I think that some updates of RETURNN break things in the converter. I'll rerun the test cases here so we can see.

### CODE REVIEW

**Comment by vieting** [comment]
It seems to be caused by this commit https://github.com/rwth-i6/returnn/commit/15a42ca30f05363ecf19f472eb35eeb18bb3e55e which was introducing `GetLayer` to fix https://github.com/rwth-i6/returnn/issues/993.

**Comment by vieting** [comment]
A couple of tests break, e.g. `test_converter.test_naming_problem`.

Full traceback

<details>

```
ERROR: test_converter.test_naming_problem
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.8/site-packages/nose/case.py", line 198, in TestBase.runTest
    line: self.test(*self.arg)
    locals:
      self = <local> test_converter.test_naming_problem
      self.test = <local> <function test_naming_problem at 0x7fbb08b811f0>
      self.arg = <local> ()
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/tests/test_converter.py", line 186, in test_naming_problem
    line: verify_torch_and_convert_to_returnn(model_func, inputs=x)
    locals:
      verify_torch_and_convert_to_returnn = <global> <function verify_torch_and_convert_to_returnn at 0x7fbb08b889d0>
      model_func = <local> <function test_naming_problem.<locals>.model_func at 0x7fbb08459430>
      inputs = <not found>
      x = <local> array([[[ 0.49671414, -0.1382643 ,  0.64768857,  1.5230298 ,
                           -0.23415338, -0.23413695,  1.5792128 ,  0.7674347 ,
                           -0.46947438,  0.54256004, -0.46341768],
                          [-0.46572974,  0.24196227, -1.9132802 , -1.7249179 ,
                           -0.5622875 , -1.0128311 ,  0.31424734, -0.9080241 ,
                      ...
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/converter/converter.py", line 432, in verify_torch_and_convert_to_returnn
    line: converter.run()
    locals:
      converter = <local> <pytorch_to_returnn.converter.converter.Converter object at 0x7fbb01990760>
      converter.run = <local> <bound method Converter.run of <pytorch_to_returnn.converter.converter.Converter object at 0x7fbb01990760>>
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/converter/converter.py", line 139, in Converter.run
    line: self._run_torch_returnn_drop_in()
    locals:
      self = <local> <pytorch_to_returnn.converter.converter.Converter object at 0x7fbb01990760>
      self._run_torch_returnn_drop_in = <local> <bound method Converter._run_torch_returnn_drop_in of <pytorch_to_returnn.converter.converter.Converter object at 0x7fbb01990760>>
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/converter/converter.py", line 277, in Converter._run_torch_returnn_drop_in
    line: out_returnn = self._model_func(wrapped_import_torch_returnn, in_returnn)
    locals:
      out_returnn = <not found>
      self = <local> <pytorch_to_returnn.converter.converter.Converter object at 0x7fbb01990760>
      self._model_func = <local> <function test_naming_problem.<locals>.model_func at 0x7fbb08459430>
      wrapped_import_torch_returnn = <global> <function wrapped_import_torch_returnn at 0x7fbb08b88940>
      in_returnn = <local> <Tensor name:? tensor:(B(3),F'feature:data'(5)(5),'time:data'[B](11)) returnn_data:'data' [B,F|F'feature:data'(5),T|'time:data'[B]] axes id>
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/tests/test_converter.py", line 182, in test_naming_problem.<locals>.model_func
    line: return model(inputs)
    locals:
      model = <local> <MainModel>
      inputs = <local> <Tensor name:? tensor:(B(3),F'feature:data'(5)(5),'time:data'[B](11)) returnn_data:'data' [B,F|F'feature:data'(5),T|'time:data'[B]] axes id>
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/torch/nn/modules/module.py", line 439, in Module.__call__
    line: res = call_entry.apply_call()
    locals:
      res = <not found>
      call_entry = <local> <CallEntry '' <ModuleEntry <MainModel>> (depth 0)>
      call_entry.apply_call = <local> <bound method CallEntry.apply_call of <CallEntry '' <ModuleEntry <MainModel>> (depth 0)>>
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/naming/call.py", line 106, in CallEntry.apply_call
    line: res = module.forward(*inputs_args, **inputs_kwargs)
    locals:
      res = <not found>
      module = <local> <MainModel>
      module.forward = <local> <function test_naming_problem.<locals>.model_func.<locals>.MainModel.forward at 0x7fbb0171b0d0>
      inputs_args = <local> (<Tensor name:? tensor:(B(3),F'feature:data'(5)(5),'time:data'[B](11)) returnn_data:'data' [B,F|F'feature:data'(5),T|'time:data'[B]] axes id>,)
      inputs_kwargs = <local> {}
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/torch/nn/modules/module.py", line 105, in wrapped_func
    line: return obj(*args, **kwargs)
    locals:
      obj = <local> <bound method test_naming_problem.<locals>.model_func.<locals>.MainModel.forward of <MainModel>>
      args = <local> (<Tensor name:? tensor:(B(3),F'feature:data'(5)(5),'time:data'[B](11)) returnn_data:'data' [B,F|F'feature:data'(5),T|'time:data'[B]] axes id>,)
      kwargs = <local> {}
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/tests/test_converter.py", line 179, in test_naming_problem.<locals>.model_func.<locals>.MainModel.forward
    line: return self.feature_extractor(x)
    locals:
      self = <local> <MainModel>
      self.feature_extractor = <local> <ConvFeatureExtractionModel>
      x = <local> <Tensor name:? tensor:(B(3),F'feature:data'(5)(5),'time:data'[B](11)) returnn_data:'data' [B,F|F'feature:data'(5),T|'time:data'[B]] axes id>
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/torch/nn/modules/module.py", line 438, in Module.__call__
    line: with naming.make_module_call(module=self, inputs_args=input, inputs_kwargs=kwargs) as call_entry:
    locals:
      naming = <local> <pytorch_to_returnn.naming.naming.Naming object at 0x7fbb01778ee0>
      naming.make_module_call = <local> <bound method Naming.make_module_call of <pytorch_to_returnn.naming.naming.Naming object at 0x7fbb01778ee0>>
      module = <not found>
      self = <local> <ConvFeatureExtractionModel>
      inputs_args = <not found>
      input = <local> (<Tensor name:? tensor:(B(3),F'feature:data'(5)(5),'time:data'[B](11)) returnn_data:'data' [B,F|F'feature:data'(5),T|'time:data'[B]] axes id>,)
      inputs_kwargs = <not found>
      kwargs = <local> {}
      call_entry = <not found>
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/naming/naming.py", line 238, in Naming.make_module_call
    line: namespace = parent_namespace.register_sub_call(entry)
    locals:
      namespace = <not found>
      parent_namespace = <local> <RegisteredName '' <ModuleEntry <MainModel>> -> ...>
      parent_namespace.register_sub_call = <local> <bound method RegisteredName.register_sub_call of <RegisteredName '' <ModuleEntry <MainModel>> -> ...>>
      entry = <local> <CallEntry '?' <ModuleEntry <ConvFeatureExtractionModel>> (depth 1)>
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/naming/namespace.py", line 192, in RegisteredName.register_sub_call
    line: child.assign_call(call)
    locals:
      child = <local> <RegisteredName 'feature_extractor' <ModuleEntry <ConvFeatureExtractionModel>> -> None>
      child.assign_call = <local> <bound method RegisteredName.assign_call of <RegisteredName 'feature_extractor' <ModuleEntry <ConvFeatureExtractionModel>> -> None>>
      call = <local> <CallEntry '?' <ModuleEntry <ConvFeatureExtractionModel>> (depth 1)>
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/naming/namespace.py", line 121, in RegisteredName.assign_call
    line: self.assign_module(call.module)
    locals:
      self = <local> <RegisteredName 'feature_extractor' <ModuleEntry <ConvFeatureExtractionModel>> -> None>
      self.assign_module = <local> <bound method RegisteredName.assign_module of <RegisteredName 'feature_extractor' <ModuleEntry <ConvFeatureExtractionModel>> -> None>>
      call = <local> <CallEntry '?' <ModuleEntry <ConvFeatureExtractionModel>> (depth 1)>
      call.module = <local> <ModuleEntry <ConvFeatureExtractionModel>>
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/naming/namespace.py", line 163, in RegisteredName.assign_module
    line: self.maybe_create_returnn_ctx()
    locals:
      self = <local> <RegisteredName 'feature_extractor' <ModuleEntry <ConvFeatureExtractionModel>> -> None>
      self.maybe_create_returnn_ctx = <local> <bound method RegisteredName.maybe_create_returnn_ctx of <RegisteredName 'feature_extractor' <ModuleEntry <ConvFeatureExtractionModel>> -> None>>
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/naming/namespace.py", line 143, in RegisteredName.maybe_create_returnn_ctx
    line: self.returnn_ctx = _returnn_ctx.ReturnnContext(
            parent=self.parent.returnn_ctx if self.parent else None,
            name=self.name, returnn_train_flag=self.returnn_train_flag)
    locals:
      self = <local> <RegisteredName 'feature_extractor' <ModuleEntry <ConvFeatureExtractionModel>> -> None>
      self.returnn_ctx = <local> None
      _returnn_ctx = <global> <module 'pytorch_to_returnn.naming.returnn_ctx' from '/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/naming/returnn_ctx.py'>
      _returnn_ctx.ReturnnContext = <global> <class 'pytorch_to_returnn.naming.returnn_ctx.ReturnnContext'>
      parent = <not found>
      self.parent = <local> <RegisteredName '' <ModuleEntry <MainModel>> -> ...>
      self.parent.returnn_ctx = <local> <ReturnnContext ''>
      name = <not found>
      self.name = <local> 'feature_extractor', len = 17
      returnn_train_flag = <not found>
      self.returnn_train_flag = <local> False
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/naming/returnn_ctx.py", line 20, in ReturnnContext.__init__
    line: self.sub_net_layer = parent.network.construct_layer(
            name=name,
            # This is just a placeholder, will be replaced in define_output.
            net_dict={name: {"class": "subnetwork", "from": "data", "subnetwork": {
              "output": {"class": "copy", "from": "data"}}}})
    locals:
      self = <local> !AttributeError: 'ReturnnContext' object has no attribute 'network'
      self.sub_net_layer = <local> !AttributeError: 'ReturnnContext' object has no attribute 'sub_net_layer'
      parent = <local> <ReturnnContext ''>
      parent.network = <local> <TFNetwork 'root' train=False>
      parent.network.construct_layer = <local> <bound method TFNetwork.construct_layer of <TFNetwork 'root' train=False>>
      name = <local> 'feature_extractor', len = 17
  File "/home/runner/.local/lib/python3.8/site-packages/returnn/tf/network.py", line 954, in TFNetwork.construct_layer
    line: layer_class.transform_config_dict(layer_desc, network=net, get_layer=get_layer)
    locals:
      layer_class = <local> <class 'returnn.tf.layers.basic.SubnetworkLayer'>
      layer_class.transform_config_dict = <local> <bound method SubnetworkLayer.transform_config_dict of <class 'returnn.tf.layers.basic.SubnetworkLayer'>>
      layer_desc = <local> {'from': 'data', 'subnetwork': {'output': {'class': 'copy', 'from': 'data'}}, '_network': <TFNetwork 'root' train=False>, '_name': 'feature_extractor', '_subnet': Subnetwork{root/feature_extractor}}
      network = <not found>
      net = <local> <TFNetwork 'root' train=False>
      get_layer = <local> <GetLayer 'root'>
  File "/home/runner/.local/lib/python3.8/site-packages/returnn/tf/layers/basic.py", line 8353, in SubnetworkLayer.transform_config_dict
    line: d["_output"] = subnet.construct_layer("output", parent_get_layer=get_layer)
    locals:
      d = <local> {'from': 'data', 'subnetwork': {'output': {'class': 'copy', 'from': 'data'}}, '_network': <TFNetwork 'root' train=False>, '_name': 'feature_extractor', '_subnet': Subnetwork{root/feature_extractor}}
      subnet = <local> Subnetwork{root/feature_extractor}
      subnet.construct_layer = <local> <bound method Subnetwork.construct_layer of Subnetwork{root/feature_extractor}>
      parent_get_layer = <not found>
      get_layer = <local> <GetLayer 'root'>
  File "/home/runner/.local/lib/python3.8/site-packages/returnn/tf/network.py", line 2998, in Subnetwork.construct_layer
    line: return self.get_sub_layer_func(parent_get_layer)(name)
    locals:
      self = <local> Subnetwork{root/feature_extractor}
      self.get_sub_layer_func = <local> <bound method Subnetwork.get_sub_layer_func of Subnetwork{root/feature_extractor}>
      parent_get_layer = <local> <GetLayer 'root'>
      name = <local> 'output', len = 6
  File "/home/runner/.local/lib/python3.8/site-packages/returnn/tf/network.py", line 3275, in GetLayer.__call__
    line: return get_layer.network.construct_layer(
            net_dict=get_layer._net_dict, name=name,
            get_layer=get_layer, add_layer=get_layer._add_layer_func)
    locals:
      get_layer = <local> <GetLayer 'root'>
      get_layer.network = <local> <TFNetwork 'root' train=False>
      get_layer.network.construct_layer = <local> <bound method TFNetwork.construct_layer of <TFNetwork 'root' train=False>>
      net_dict = <not found>
      get_layer._net_dict = <local> {}
      name = <local> 'feature_extractor/output', len = 24
      add_layer = <not found>
      get_layer._add_layer_func = <local> None
  File "/home/runner/.local/lib/python3.8/site-packages/returnn/tf/network.py", line 885, in TFNetwork.construct_layer
    line: raise LayerNotFound(
            "layer %r not found in %r" % (name, self), layer_name=full_name, network=self, net_dict=net_dict)
    locals:
      LayerNotFound = <global> <class 'returnn.tf.network.LayerNotFound'>
      name = <local> 'feature_extractor', len = 17
      self = <local> <TFNetwork 'root' train=False>
      layer_name = <not found>
      full_name = <local> 'feature_extractor/output', len = 24
      network = <not found>
      net_dict = <local> {}
returnn.tf.network.LayerNotFound: layer 'feature_extractor' not found in <TFNetwork 'root' train=False>
```

</details>

**Comment by albertz** [comment]
It would be helpful to also have a pure RETURNN test (pure RETURNN net dict) for this, and then an issue on RETURNN side.

**Comment by vieting** [comment]
Also `test_converter.test_weight_norm`, `test_converter.test_custom_layer_norm`, `test_converter.test_naming_problem`, `ERROR: test_converter.test_naming_inner_func_functional_with_buffer`. It's always the error.
```
returnn.tf.network.LayerNotFound: layer '...' not found in <TFNetwork 'root' train=False>
```

**Comment by vieting** [comment]
> It would be helpful to also have a pure RETURNN test (pure RETURNN net dict) for this, and then an issue on RETURNN side.

I'll do that.

**Comment by vieting** [comment]
See https://github.com/rwth-i6/returnn/issues/1014 for a pure RETURNN test.

**Comment by albertz** [comment]
I don't think there needs anything to be done here in pytorch-to-returnn if this RETURNN issue is the only problem. Let's wait until https://github.com/rwth-i6/returnn/pull/1015 is merged and then rerun the tests here.

**Pull request closed without merging**
