### PR TITLE
add torch.sum and Tensor.sum

### PR DESCRIPTION
**Pull request by vieting**
Use RETURNN's `ReduceLayer` to add `torch.sum` and `Tensor.sum`.

### CODE REVIEW

**Comment by vieting** [comment]
I just saw that I'm overriding the inbuilt `sum` in `functional` which is not a good idea. I don't actually need to have it in `functional`, but in PyTorch it's available as `torch.sum` and we usually have these functions in `functional.py`. Where should we put this here instead?

**Comment by albertz** [comment]
> I just saw that I'm overriding the inbuilt `sum` in `functional` which is not a good idea. I don't actually need to have it in `functional`, but in PyTorch it's available as `torch.sum` and we usually have these functions in `functional.py`. Where should we put this here instead?

I don't understand the problem. Wherever you define it, you would overwrite the `sum` builtin. Why is it a problem specifically in `functional`? And why is overwriting the builtin `sum` a problem? If you need the builtin `sum` elsewhere in the module, you can simply do:
```
_builtin_sum = sum

...

def sum(...):
  ...
```

**Review by albertz — APPROVED** [review]
Looks good. Have you tested it?

**Comment by albertz** [comment]
I wonder whether we should first fix the issue with RETURNN (#78).

**Comment by vieting** [comment]
> I wonder whether we should first fix the issue with RETURNN (#78), and then rebase here to check that all tests run through.

Yes, that was my plan.

**Comment by albertz** [comment]
I think this needs a rebase now for the new `reuse_params` logic.

**Comment by vieting** [comment]
>I think this needs a rebase now for the new reuse_params logic.

It's now rebased and all tests pass.

**Pull request merged**
